tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline": "#70787c",
                "tertiary": "#4f2400",
                "on-primary-fixed": "#001f29",
                "on-surface-variant": "#40484c",
                "inverse-surface": "#2e3132",
                "surface-container-highest": "#e1e3e4",
                "surface-container-high": "#e7e8e9",
                "error": "#ba1a1a",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "outline-variant": "#c0c8cc",
                "surface-bright": "#f8f9fa",
                "on-primary-container": "#83bdd4",
                "surface-tint": "#28657a",
                "inverse-primary": "#95cfe7",
                "on-background": "#191c1d",
                "surface-variant": "#e1e3e4",
                "secondary-fixed-dim": "#82db7e",
                "on-tertiary-container": "#ff9c54",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "surface-dim": "#d9dadb",
                "secondary": "#106d20",
                "primary": "#003544",
                "error-container": "#ffdad6",
                "on-secondary-fixed": "#002204",
                "on-secondary-fixed-variant": "#005312",
                "tertiary-fixed": "#ffdcc6",
                "secondary-fixed": "#9df898",
                "on-surface": "#191c1d",
                "surface-container-lowest": "#ffffff",
                "background": "#f8f9fa",
                "surface": "#f8f9fa",
                "on-primary-fixed-variant": "#014d61",
                "secondary-container": "#9df898",
                "primary-fixed-dim": "#95cfe7",
                "tertiary-container": "#713600",
                "primary-container": "#004d61",
                "on-secondary-container": "#1a7425",
                "tertiary-fixed-dim": "#ffb786",
                "on-tertiary-fixed-variant": "#723600",
                "on-tertiary-fixed": "#311300",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "primary-fixed": "#b9eaff",
                "inverse-on-surface": "#f0f1f2",
                "surface-container": "#edeeef"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}
